version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: video_user
      POSTGRES_PASSWORD: video_password
      POSTGRES_DB: sred_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U video_user -d sred_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
