"""add_segment_offsets

Revision ID: 06c01b26649c
Revises: d272c1cd5cb4
Create Date: 2026-01-31 22:10:40.851181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c01b26649c'
down_revision: Union[str, Sequence[str], None] = 'd272c1cd5cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable first
    op.add_column('docsegment', sa.Column('start_offset', sa.Integer(), nullable=True))
    op.add_column('docsegment', sa.Column('end_offset', sa.Integer(), nullable=True))
    
    # Fill existing rows with default value
    op.execute("UPDATE docsegment SET start_offset = 0, end_offset = 0 WHERE start_offset IS NULL")
    
    # Now set them to NOT NULL
    op.alter_column('docsegment', 'start_offset', nullable=False)
    op.alter_column('docsegment', 'end_offset', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docsegment', 'end_offset')
    op.drop_column('docsegment', 'start_offset')
    # ### end Alembic commands ###
