"""drop_project_and_projectsegmentlink_tables

Revision ID: 6a5589fb8054
Revises: 6f1889934df6
Create Date: 2026-02-02 01:35:44.861248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a5589fb8054'
down_revision: Union[str, Sequence[str], None] = '6f1889934df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projectsegmentlink')
    op.drop_index(op.f('ix_project_source_anchor'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_anchor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name='project_workspace_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='project_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_project_source_anchor'), 'project', ['source_anchor'], unique=False)
    op.create_table('projectsegmentlink',
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('segment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('link_type', postgresql.ENUM('STRONG_ANCHOR', 'WEAK_INFERENCE', name='linktype'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('projectsegmentlink_project_id_fkey')),
    sa.ForeignKeyConstraint(['segment_id'], ['docsegment.id'], name=op.f('projectsegmentlink_segment_id_fkey')),
    sa.PrimaryKeyConstraint('project_id', 'segment_id', name=op.f('projectsegmentlink_pkey'))
    )
    # ### end Alembic commands ###
