"""drop_pgvector_embedding_column

Revision ID: 6f1889934df6
Revises: f9590c7da3a0
Create Date: 2026-02-02 00:01:40.870515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1889934df6'
down_revision: Union[str, Sequence[str], None] = 'f9590c7da3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docsegment', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docsegment', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
