"""add_entity_anchors

Revision ID: c62112cd3ef7
Revises: 06c01b26649c
Create Date: 2026-02-01 20:15:03.918624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c62112cd3ef7'
down_revision: Union[str, Sequence[str], None] = '06c01b26649c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entityanchor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('segment_id', sa.Uuid(), nullable=False),
    sa.Column('anchor_type', sa.Enum('TICKET', 'PR', 'FILE_REF', 'ERROR_CODE', name='anchortype'), nullable=False),
    sa.Column('anchor_value', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['docsegment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entityanchor_anchor_value'), 'entityanchor', ['anchor_value'], unique=False)
    op.create_index(op.f('ix_entityanchor_segment_id'), 'entityanchor', ['segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entityanchor_segment_id'), table_name='entityanchor')
    op.drop_index(op.f('ix_entityanchor_anchor_value'), table_name='entityanchor')
    op.drop_table('entityanchor')
    # ### end Alembic commands ###
