"""add_segment_structure

Revision ID: d272c1cd5cb4
Revises: 402614c761a6
Create Date: 2026-01-31 21:46:36.702075

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd272c1cd5cb4'
down_revision: Union[str, Sequence[str], None] = '402614c761a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add sequence_index as nullable first
    op.add_column('docsegment', sa.Column('sequence_index', sa.Integer(), nullable=True))
    
    # Fill existing rows with default value
    op.execute("UPDATE docsegment SET sequence_index = 0 WHERE sequence_index IS NULL")
    
    # Now set it to NOT NULL
    op.alter_column('docsegment', 'sequence_index', nullable=False)
    
    op.add_column('docsegment', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.add_column('docsegment', sa.Column('context_before', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('docsegment', sa.Column('context_after', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key('fk_docsegment_parent_id', 'docsegment', 'docsegment', ['parent_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'docsegment', type_='foreignkey')
    op.drop_column('docsegment', 'context_after')
    op.drop_column('docsegment', 'context_before')
    op.drop_column('docsegment', 'parent_id')
    op.drop_column('docsegment', 'sequence_index')
    # ### end Alembic commands ###
