"""add_compliance_fields

Revision ID: f9590c7da3a0
Revises: c62112cd3ef7
Create Date: 2026-02-01 23:07:37.810151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9590c7da3a0'
down_revision: Union[str, Sequence[str], None] = 'c62112cd3ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workcluster', sa.Column('tech_uncertainty', sa.Text(), nullable=True))
    op.add_column('workcluster', sa.Column('tech_advancement', sa.Text(), nullable=True))
    op.add_column('workcluster', sa.Column('systematic_investigation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workcluster', 'systematic_investigation')
    op.drop_column('workcluster', 'tech_advancement')
    op.drop_column('workcluster', 'tech_uncertainty')
    # ### end Alembic commands ###
